# Automatically build the project and run any configured tests for every push
# and submitted pull request. This can help catch issues that only occur on
# certain platforms or Java versions, and provides a first line of defence
# against bad commits.

name: build
on:
  pull_request:
    paths:
      - "common/**"
      - "fabric/**"
      - "buildSrc/**"
      - "versionProperties/**"
      - "build.gradle"
      - "gradle.properties"
      - "settings.gradle"
      - ".github/workflows/build.yml"
  push:
    paths:
      - "common/**"
      - "fabric/**"
      - "buildSrc/**"
      - "versionProperties/**"
      - "build.gradle"
      - "gradle.properties"
      - "settings.gradle"
      - ".github/workflows/build.yml"

jobs:
  get-versions:
    runs-on: ubuntu-24.04
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: read versions from versionProperties
        id: set-matrix
        run: |
          versions=$(ls versionProperties/*.properties 2>/dev/null | xargs -n1 basename | sed 's/.properties$//' | grep -v gitkeep | jq -R -s -c 'split("\n") | map(select(length > 0))')
          echo "matrix=$versions" >> $GITHUB_OUTPUT

  build:
    needs: get-versions
    strategy:
      fail-fast: false
      matrix:
        mc_ver: ${{ fromJson(needs.get-versions.outputs.matrix) }}
    runs-on: ubuntu-24.04
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v4
      - name: setup jdk
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'microsoft'
      - name: make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: test
        run: ./gradlew :common:test -Pmc_ver=${{ matrix.mc_ver }}
      - name: build
        run: ./gradlew :fabric:build -Pmc_ver=${{ matrix.mc_ver }}
      - name: capture build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts-${{ matrix.mc_ver }}
          path: fabric/build/libs/