# 1.21.11 Configuration
java_version=21
minecraft_version=1.21.11
loader_version=0.18.3
loom_version=1.15-SNAPSHOT
fabric_version=0.141.1+1.21.11
cloth_config_version=21.11.153
modmenu_version=17.0.0-beta.2
owo_version=0.13.0+1.21.11
# kdl_version=1.0.1
builds_for=fabric
ui_version=21

# Modrinth Metadata
modrinth_slug=screenshot-manager-enhanced
modrinth_id=xs5bRkXn
modrinth_game_versions=1.21.11
modrinth_mod_loaders=fabric
modrinth_required_dependencies=modmenu, cloth-config