# 26.2 Configuration
java_version=25
minecraft_version=26.2
loader_version=0.19.5
loom_version=1.17-SNAPSHOT
fabric_version=0.161.0+26.2
cloth_config_version=26.2.155
modmenu_version=20.0.2
owo_version=0.13.1+26.2
# kdl_version=1.0.1
builds_for=fabric
ui_version=26-2

# Modrinth Metadata
modrinth_slug=screenshot-manager-enhanced
modrinth_id=xs5bRkXn
modrinth_game_versions=26.2
modrinth_mod_loaders=fabric
modrinth_required_dependencies=modmenu, cloth-config
